{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
  namespace: {{ $.Values.namespace }}
spec:
  type: {{ $svc.type }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}
