---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  labels:
    app: api-gateway-label

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway-label

  template:
    metadata:
      labels:
        app: api-gateway-label

    spec:
      containers:
        - name: api-gateway
          image: 194680606620.dkr.ecr.ap-south-1.amazonaws.com/petclinic-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker  
 

---
apiVersion: v1
kind: Service

metadata:
  name: api-gateway-service

spec:
  selector:
    app: api-gateway-label

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: LoadBalancer     