---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: customers-service
  labels:
    app: customers-service-label

spec:
  replicas: 1

  selector:
    matchLabels:
      app: customers-service-label

  template:
    metadata:
      labels:
        app: customers-service-label

    spec:
      containers:
        - name: customers-service
          image: 194680606620.dkr.ecr.ap-south-1.amazonaws.com/petclinic-customers-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-secret
                  key: host

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-secret
                  key: dbname

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-secret
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-secret
                  key: password

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_HOST):3306/$(DB_NAME)"

---
apiVersion: v1
kind: Service

metadata:
  name: customers-service-service

spec:
  selector:
    app: customers-service-label

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

  type: ClusterIP