apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-rds-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: petclinic-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: petclinic/rds-v2
        property: username
    - secretKey: password
      remoteRef:
        key: petclinic/rds-v2
        property: password
    - secretKey: host
      remoteRef:
        key: petclinic/rds-v2
        property: host
    - secretKey: dbname
      remoteRef:
        key: petclinic/rds-v2
        property: dbname