namespace: default

image:
  registry: 194680606620.dkr.ecr.ap-south-1.amazonaws.com
  tag: latest
  pullPolicy: Always

database:
  host: petclinic-mysql.c5ysw8q20zq1.ap-south-1.rds.amazonaws.com

services:
  admin-server-service:
    image: petclinic-admin-server
    port: 9090
    replicas: 1
    type: ClusterIP

  config-server-service:
    image: petclinic-config-server
    port: 8888
    replicas: 1
    type: ClusterIP

  discovery-server-service:
    image: petclinic-discovery-server
    port: 8761
    replicas: 1
    type: ClusterIP

  api-gateway-service:
    image: petclinic-api-gateway
    port: 8080
    replicas: 1
    type: LoadBalancer

  customers-service:
    image: petclinic-customers-service
    port: 8081
    replicas: 1
    type: ClusterIP
    database: customers

  visits-service:
    image: petclinic-visits-service
    port: 8082
    replicas: 1
    type: ClusterIP
    database: visits

  vets-service:
    image: petclinic-vets-service
    port: 8083
    replicas: 1
    type: ClusterIP
    database: vets

  genai-service:
    image: petclinic-genai-service
    port: 8084
    replicas: 1
    type: ClusterIP